language: node_js
node_js: "node"
cache: npm
env:
  - PYTHON=/usr/bin/python2.7
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
